"""added: session_id in chat

Revision ID: bd5a9c125676
Revises: 99ab11282030
Create Date: 2025-05-11 02:14:12.376725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5a9c125676'
down_revision: Union[str, None] = '99ab11282030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('session_id', sa.Integer(), nullable=True))
    op.execute('UPDATE chat SET session_id = 0 WHERE session_id IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'session_id')
    # ### end Alembic commands ###
