"""add: session

Revision ID: f3af8e5f097a
Revises: b0f622538339
Create Date: 2025-05-11 06:10:39.130191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3af8e5f097a'
down_revision: Union[str, None] = 'b0f622538339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'summary')
    # ### end Alembic commands ###
